backend:
  name: github
  repo: jmcare2024/monblog
  branch: principal  # Mets "main" si ta branche s'appelle "main"

media_folder: "images/uploads" # Stockage des images sur GitHub
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
